#pragma once

#include "BluuGnome.h"
#include "Books.h"
#include "CanyonMag.cpp"
#include "CBrennen.h"
#include "DescenteCanyon.h"
#include "Martinique.cpp"
#include "RoadTripRyan.h"
#include "UKCanyonGuides.h"
#include "Reunion.h"
#include "SuperAmazingMap.cpp"
#include "SwissCanyon.h"
#include "Tahiti.cpp"
#include "ToddMartin.cpp"
#include "Wikiloc.h"
#include "ZionCanyoneering.cpp"

#include "ShortBetaSites.cpp"
#include "ShortBetaSitesUnclassed.h"
